In [7]:
import skimage.io as io

In [10]:
label = io.imread('../data/raw/FASSEG_v2/Labels/9.bmp')

In [19]:
img = io.imread('../data/raw/FASSEG_v2/RGB/9.bmp')

In [20]:
import matplotlib.pyplot as plt

In [21]:
import numpy as np

In [24]:
comb = np.hstack((img, label))

In [26]:
io.imsave('../data/icon.jpeg', comb)

In [1]:
import sys
sys.path.append('../src')
import feature_processing as ftp

In [41]:
x, y = ftp.create_pixel_loc((2,2))

In [24]:
import numpy as np
z = np.array([[1,2], [3, 4]])
z

array([[1, 2],
       [3, 4]])

In [25]:
z.flatten()

array([1, 2, 3, 4])

In [45]:
x

array([0. , 0.5, 0. , 0.5])

In [26]:
y

array([0. , 0. , 0.5, 0.5])

In [28]:
    def _create_loc_features(array_shape, single_image=False):
        """

        Args:
            x (type): Image to flip

        Returns:
            Augmented image
        """

        if single_image:
            array_shape = (1, ) + array_shape

        x, y = create_pixel_loc(array_shape[1:3])
        x = np.tile(x, array_shape[0]).reshape(-1, 1)
        y = np.tile(y, array_shape[0]).reshape(-1, 1)

        return np.hstack((x, y))

In [31]:
def create_pixel_loc(shape):
    """Create 

    Args:
        shape (type): Image to flip

    Returns:
        Augmented image
    """
    row_ = np.array(range(0, shape[0] * shape[1]))
    y = row_.reshape(shape[0], shape[1]).T.flatten() % shape[1]
    x = row_ % shape[1]
    return x / shape[1], y / shape[1]

In [38]:
loc = _create_loc_features((2, 2), single_image=True)

In [40]:
loc[1]

array([0.5, 0. ])

In [ ]:
ftp.